apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-security-ui
  labels:
    name: product-security-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-security-ui
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: product-security-ui
    spec:
      containers:
      - name: product-security-ui
        image: product-security-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort:  80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---

kind: Service
apiVersion: v1
metadata:
  name: product-security-ui
  labels:
    name: product-security-ui
spec:
  selector:
    app: product-security-ui
  ports:
  - protocol: TCP
    port:  80
    targetPort:  80
    nodePort: 30170
  type:  NodePort
